bootstrap:
  excludes: []
  pre-deployment-remote-commands: []
  post-deployment-remote-commands: []

recurring:
  excludes: []
  pre-deployment-remote-commands: []
  post-deployment-remote-commands: []
